name: "PROD DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: prod
      aws-assume-role-arn: "arn:aws:iam::559050241395:role/github-actions-joaovictormcz-pipeline"
      aws-region: "us-east-1"
      aws-statefile-s3-bucket: "joaovictormcz-sa-east-1-terraforn-statefile"
      aws-lock-dynamodb-table: "joaovictormcz-sa-east1-terraform-lock"
